routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Authentication
Route::get(str_slug(trans('app.login')), 'Auth\LoginController@showLoginForm')->name('login');
Route::post(str_slug(trans('app.login')), 'Auth\LoginController@login');
Route::post(str_slug(trans('app.logout')), 'Auth\LoginController@logout')->name('logout');

// Registration
Route::get(str_slug(trans('app.register')), 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post(str_slug(trans('app.register')), 'Auth\RegisterController@register');

// Password Reset
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Application
Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // Base views
    Route::get('add-journeys', 'App\ViewController@index')->name('add-journeys');
    Route::get('compare', 'App\ViewController@index')->name('compare');
    Route::get('leaderboard', 'App\ViewController@index')->name('leaderboard');

    // User
    Route::get('my-account', 'MyAccountController@getAccount')->name('my-account.edit');
    Route::post('my-account', 'MyAccountController@postAccount')->name('my-account.update');
//  Route::get('my-classroom', 'MyAccountController@getClassroom')->name('my-classroom.edit');

    // App
    Route::group(['prefix' => 'app'], function () {

        Route::get('trips', 'App\JourneysController@index');
        Route::post('trips', 'App\JourneysController@index');

        Route::get('leaderboard', 'App\LeaderboardController@index');

        Route::get('compare/class', 'App\CompareController@classroom');
        Route::get('compare/year', 'App\CompareController@year');
        Route::get('compare/school', 'App\CompareController@school');

    });

    // Admin
    Route::group(['prefix' => 'admin'], function () {

        Route::get('options', 'Admin\OptionController@getOptions')->name('options.index');
        Route::post('options', 'Admin\OptionController@postOptions')->name('options.update');

        Route::resource('competitions', 'Admin\CompetitionsController');
        Route::resource('modes', 'Admin\ModesController', ['except' => ['create', 'destroy']]);

        Route::resource('local-authorities', 'Admin\LocalAuthoritiesController');
        Route::resource('schools', 'Admin\SchoolsController');
        Route::resource('classrooms', 'Admin\ClassroomsController');
        Route::resource('users', 'Admin\UsersController');
        Route::resource('pages', 'Admin\PagesController', ['only' => ['index', 'edit', 'update']]);

        Route::get('reports', 'Admin\ReportController@getIndex')->name('reports.index');
        Route::get('reports/users', 'Admin\ReportController@getUsersReport')->name('reports.users');
        Route::get('reports/schools', 'Admin\ReportController@getSchoolsReport')->name('reports.schools');
        Route::get('reports/trips', 'Admin\ReportController@getTripsReport')->name('reports.trips');
        Route::get('reports/year-group', 'Admin\ReportController@getYearGroupReport')->name('reports.year-group');

        Route::resource('trips', 'Admin\TripsController');

        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

});

Route::get('how-it-works', ['uses' => 'CustomPageController@getPage'])->name('how-it-works');
Route::get('terms-and-conditions', ['uses' => 'CustomPageController@getPage'])->name('terms-and-conditions');
Route::get('privacy-statement', ['uses' => 'CustomPageController@getPage'])->name('privacy-statement');

// Public
Route::get('leaderboard-public', 'App\ViewController@index')->name('leaderboard-public');
Route::group(['prefix' => 'app'], function () {
    Route::get('leaderboard-public', 'App\LeaderboardController@index');
});

app/Page.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Page extends Model
{
  use SoftDeletes;

  protected $fillable = [
    'name',
    'url',
    'body',
  ];

  //region Accessors

  public function getHtmlAttribute()
  {

    // create markdown parser
    $parser = new \cebe\markdown\Markdown();

    // parse the markdown and add it to the model
    return $parser->parse($this->body);
  }

  //endregion
}

resources/views/app.blade.php
@extends('layouts.app')

@section('content')

    <?php include_once("img/svg/sprite.svg"); ?>
    <div id="app"></div>
    <script src="{!! elixir('js/app.js') !!}"></script>

@endsection

resources/views/dashboard.blade.php
@extends('layouts.admin')

@section('title', 'Teacher')

@section('content')

    @include('flash::message')
    <div class="jumbotron">
        @if($morning)
            <h1>Good morning</h1>
        @else
            <h1>Good afternoon</h1>
        @endif

        <!-- <p>{{ ucfirst(trans('app.competition')) }} runs from {{ app('competition')->start_date->format(app('options')->date_format_short) }} to {{ app('competition')->end_date->format(app('options')->date_format_short) }}</p> -->
        <div id="dashboard-menu" class="row">
            @if(!empty($user->classroom))
                <div class="col-xs-3">
                    <a class="c-btn c-btn--green" href="{{ route('add-journeys') }}">
                        <span class="c-btn__content"><span class="fa fa-fw fa-plus"></span>Add Journeys</span>
                    </a>
                </div>
                <div class="col-xs-3">
                    <a class="c-btn c-btn--green" href="{{ route('compare') }}">
                        <span class="c-btn__content"><span class="fa fa-fw fa-plus"></span>Compare</span>
                    </a>
                </div>
            @endif
            @if(auth()->user()->can('super') || !empty($user->classroom))
                <div class="col-xs-3">
                    <a class="c-btn c-btn--green" href="{{ route('leaderboard') }}">
                        <span class="c-btn__content"><span class="fa fa-fw fa-plus"></span>Leaderboard</span>
                    </a>
                </div>
            @endif
            @can('super')
                <div class="col-xs-3">
                    <a class="c-btn c-btn--green" href="{{ route('users.index') }}"><span class="c-btn__content"><span class="fa fa-fw fa-plus"></span>Add Teachers</span></a>
                </div>
            @endcan
            @can('admin')
                <div class="col-xs-3">
                    <a class="c-btn c-btn--green" href="{{ route('classrooms.index') }}"><span class="c-btn__content"><span class="fa fa-fw fa-plus"></span>Add {{ ucfirst(trans('app.classrooms')) }}</span></a>
                </div>
            @endcan

            <div class="col-xs-3">
                <a class="c-btn c-btn--green" href="{{ route('how-it-works') }}">
                    <span class="c-btn__content">How it works</span>
                </a>
            </div>

        </div>

        <div id="dashboard-warning" class="row hide">
            <div class="panel panel-default">
                <div class="panel-warning">
                    <div class="panel-heading">
                        <h1 class="panel-title">Update your browser!</h1>
                    </div>
                    <div class="panel-body">
                        The Somerset Schools Challenge website has been designed to work with modern web browsers. We have detected that you are not using one of our recommended browsers and would strongly suggest you ask your IT department to upgrade you.<br/><br/>Please use one of the links below for more information:<br/><br/>
                        <div class="form-group">
                            <a class="btn btn-link btn-block" href='http://www.apple.com/safari' target='_blank'>Apple Safari</a>
                            <a class="btn btn-link btn-block" href='https://www.google.com/chrome' target='_blank'>Google Chrome</a>
                            <a class="btn btn-link btn-block" href='http://windows.microsoft.com/en-us/internet-explorer/download-ie' target='_blank'>Microsoft Internet Explorer</a>
                            <a class="btn btn-link btn-block" href='http://www.browserfordoing.com' target='_blank'>Microsoft Edge</a>
                            <a class="btn btn-link btn-block" href='https://www.mozilla.org/en-US/firefox/new' target='_blank'>Mozilla Firefox</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/my-account.blade.php
@extends('layouts.admin')

@section('title', 'My Account')

@section('content')

    @include('flash::message')
    <div class="page-header">
        <h1>My Account</h1>
    </div>
    {{ Form::model($model, ['route' => ['my-account.update'], 'files' => true]) }}
    {{ Form::bsText('email', 'Email',  $model->email, ['required']) }}
    {{ Form::bsText('display_name', 'Display name <small>(optional)</small>', $model->display_name, ['placeholder' => 'What shall we call you?']) }}
    {{ Form::bsText('first_name', 'First name <small>(optional)</small>', $model->first_name) }}
    {{ Form::bsText('last_name', 'Last name <small>(optional)</small>', $model->last_name) }}
    @can('super')
    {{ Form::bsSelect('school_id', 'School', $model->school_id, $schoolList) }}
    @endcan
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
    {{ Form::close() }}

@endsection

resources/views/page.blade.php
@extends('layouts.custom-page')

@section('title', $model->name)

@section('content')

    {!! $model->html !!}

@endsection

resources/views/test.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>
<form action="/app/trips" method="post">
    {{ csrf_field() }}
    <div>
        <label for="data">Data</label>
        <input type="text" name="data" value="" />
    </div>
    <button type="submit">Submit</button>
</form>
</body>
</html>