routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Authentication
Route::get(str_slug(trans('app.login')), 'Auth\LoginController@showLoginForm')->name('login');
Route::post(str_slug(trans('app.login')), 'Auth\LoginController@login');
Route::post(str_slug(trans('app.logout')), 'Auth\LoginController@logout')->name('logout');

// Registration
Route::get(str_slug(trans('app.register')), 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post(str_slug(trans('app.register')), 'Auth\RegisterController@register');

// Password Reset
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Application
Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // Base views
    Route::get('add-journeys', 'App\ViewController@index')->name('add-journeys');
    Route::get('compare', 'App\ViewController@index')->name('compare');
    Route::get('leaderboard', 'App\ViewController@index')->name('leaderboard');

    // User
    Route::get('my-account', 'MyAccountController@getAccount')->name('my-account.edit');
    Route::post('my-account', 'MyAccountController@postAccount')->name('my-account.update');
//  Route::get('my-classroom', 'MyAccountController@getClassroom')->name('my-classroom.edit');

    // App
    Route::group(['prefix' => 'app'], function () {

        Route::get('trips', 'App\JourneysController@index');
        Route::post('trips', 'App\JourneysController@index');

        Route::get('leaderboard', 'App\LeaderboardController@index');

        Route::get('compare/class', 'App\CompareController@classroom');
        Route::get('compare/year', 'App\CompareController@year');
        Route::get('compare/school', 'App\CompareController@school');

    });

    // Admin
    Route::group(['prefix' => 'admin'], function () {

        Route::get('options', 'Admin\OptionController@getOptions')->name('options.index');
        Route::post('options', 'Admin\OptionController@postOptions')->name('options.update');

        Route::resource('competitions', 'Admin\CompetitionsController');
        Route::resource('modes', 'Admin\ModesController', ['except' => ['create', 'destroy']]);

        Route::resource('local-authorities', 'Admin\LocalAuthoritiesController');
        Route::resource('schools', 'Admin\SchoolsController');
        Route::resource('classrooms', 'Admin\ClassroomsController');
        Route::resource('users', 'Admin\UsersController');
        Route::resource('pages', 'Admin\PagesController', ['only' => ['index', 'edit', 'update']]);

        Route::get('reports', 'Admin\ReportController@getIndex')->name('reports.index');
        Route::get('reports/users', 'Admin\ReportController@getUsersReport')->name('reports.users');
        Route::get('reports/schools', 'Admin\ReportController@getSchoolsReport')->name('reports.schools');
        Route::get('reports/trips', 'Admin\ReportController@getTripsReport')->name('reports.trips');
        Route::get('reports/year-group', 'Admin\ReportController@getYearGroupReport')->name('reports.year-group');

        Route::resource('trips', 'Admin\TripsController');

        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

});

Route::get('how-it-works', ['uses' => 'CustomPageController@getPage'])->name('how-it-works');
Route::get('terms-and-conditions', ['uses' => 'CustomPageController@getPage'])->name('terms-and-conditions');
Route::get('privacy-statement', ['uses' => 'CustomPageController@getPage'])->name('privacy-statement');

// Public
Route::get('leaderboard-public', 'App\ViewController@index')->name('leaderboard-public');
Route::group(['prefix' => 'app'], function () {
    Route::get('leaderboard-public', 'App\LeaderboardController@index');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
  use Notifiable;
  use SoftDeletes;

  protected $fillable = [
    'email',
    'school_id',
    'display_name',
    'first_name',
    'last_name',
    'is_admin',
    'is_super',
    'last_login',
    'last_login_ip',
    'password',
  ];

  protected $hidden = [
    'is_admin',
    'is_super',
    'last_login',
    'last_login_ip',
    'password',
    'remember_token',
    'created_at',
    'updated_at',
    'deleted_at'
  ];

  protected $dates = [
    'last_login',
    'created_at',
    'updated_at',
    'deleted_at'
  ];

  protected $casts = [
    'is_admin' => 'boolean',
    'is_super' => 'boolean',
  ];

  protected $appends = [
    'full_name',
  ];

  //region Events

//  protected static function boot()
//  {
//    parent::boot();
//
//    // set up new scope
//    $scope = new SortScope();
//    $self = new static;
//    $scope->attributes = $self->fillable;
//    static::addGlobalScope($scope);
//
//  }

  //endregion

  //region Relations

  public function classrooms()
  {
    return $this->belongsToMany(Classroom::class)->withTimestamps();
  }

  public function school()
  {
    return $this->belongsTo(School::class);
  }

  //endregion

  //region Authorization

  public function isAdmin()
  {
    return $this->is_admin;
  }

  public function isSuper()
  {
    return $this->is_super;
  }

  public function isTeacher()
  {
    return \DB::table('classroom_user')->select('user_id')->where('user_id', '=', auth()->user()->id)->count();
  }

//  public function owns($related)
//  {
//    return $this->id == $related->user_id;
//  }

  //endregion

  //region Accessors

  public function getClassroomAttribute()
  {
    return $this->classrooms->first();
  }

  public function getFullNameAttribute()
  {
    return $this->first_name . ' ' . $this->last_name;
  }

  public function getPrimaryNameAttribute()
  {

    // always return display name if present
    if (!empty($this->display_name)) {
      return $this->display_name;
    }

    // secondly, try the first name
    if (!empty($this->first_name)) {
      return $this->first_name;
    }

    // finally create a name using the users id
    return 'user' . $this->id;
  }

  //endregion

  //region Mutators

  public function setEmailAttribute($value)
  {
    $this->attributes['email'] = empty($value) ? null : strtolower(trim($value));
  }

  public function setDisplayNameAttribute($value)
  {
    $this->attributes['display_name'] = empty($value) ? null : trim($value);
  }

  public function setFirstNameAttribute($value)
  {
    $this->attributes['first_name'] = empty($value) ? null : trim($value);
  }

  public function setLastNameAttribute($value)
  {
    $this->attributes['last_name'] = empty($value) ? null : trim($value);
  }

  //endregion

  //region Static

  public static function selectList($school_id = null, $teacher_id = null)
  {
    // set up the query
    $query = User::query();

    // define the relation
    $relation = 'classrooms';

    // add the relation
    if (!empty($relation)) {
      $query = $query->with($relation);
    }

    // filter if necessary
    if (!empty($school_id)) {
      $query = $query->where('school_id', '=', $school_id);
    }

    // run the query
    $collection = $query
      ->orderBy('email', 'asc')
      ->get();

    // prepare the list
    $selectList = [];
    foreach ($collection as $model) {

      // default text
      //$assigned_text = '';

      // assigned text
      if (empty($model->classroom) || $model->id == $teacher_id) {
        //$assigned_text = ' - unassigned';
        // build the string
        //$selectList[$model->id] = $model->display_name . $assigned_text;
        $selectList[$model->id] = $model->first_name.' '.$model->last_name;
      }

    }

    // add the 'Please select' option
    $selectList = pleaseSelect($selectList);

    return $selectList;
  }

  //endregion

}

resources/views/partials/browserdetect.blade.php
<script>
var initCheck=true;
document.onreadystatechange = function(){
	if(initCheck){ 
		initCheck=false;
		if(getIEVersion()){ 
			if(document.getElementsByClassName("panel-login").length){ // login
				document.getElementsByClassName("panel-login")[0].className+=" hide";
				document.getElementsByClassName("panel-warning")[0].className="panel-warning";
			}else{ // dashboard
				document.getElementById("dashboard-menu").className+=" hide";
				document.getElementById("dashboard-warning").className="row";
			}
		}
	}
}

function getIEVersion() {
	var sAgent = window.navigator.userAgent;
	var Idx = sAgent.indexOf("MSIE");

	// If IE, return version number.
	if (Idx > 0) 
	  return parseInt(sAgent.substring(Idx+ 5, sAgent.indexOf(".", Idx)));

	// If IE 11 then look for Updated user agent string.
	else if (!!navigator.userAgent.match(/Trident\/7\./)) 
	  //return 11;
	  return false;

	else
	  //return 0; //It is not IE
	  return false;
}
</script>

resources/views/partials/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <span><span class="fa fa-copyright fa-fw"></span> {{ $today->format('Y') }} Somerset County Council</span>
                <span> | </span>
                <a href="{{ route('terms-and-conditions') }}">Terms and conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/google-analytics.blade.php
@if(!empty($options->google_code))
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', '{{ $options->google_code }}', 'auto');
        ga('send', 'pageview');
    </script>
@endif

resources/views/partials/logout.blade.php
<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
    Logout <span class="fa fa-sign-out fa-fw"></span>
</a>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>

resources/views/partials/masthead.blade.php
<div class="masthead">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>Masthead</h1>
                <ul>
                    <li>Logged in as {{ $user->full_name }}</li>
                    <li><a href="{{ route('my-account.edit') }}">My Account</a></li>
                    <li>@include('partials.logout')</li>
                </ul>
                <hr>
            </div>
        </div>
    </div>
</div>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('dashboard') }}">{{ config('app.name') }}</a>
        </div>
        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                @if (Auth::guest())
                    <li><a href="{{ route('login') }}">{{ ucfirst(trans('app.login')) }}</a></li>
                    <li><a href="{{ route('register') }}">{{ ucfirst(trans('app.register')) }}</a></li>
                @else
                    <li><a href="{{ route('dashboard') }}">Dashboard</a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Manage <span class="fa fa-caret-down"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @can('super')
                                <li><a href="{{ route('options.index') }}"><span class="fa fa-cogs fa-fw"></span> Options</a></li>
                                <li><a href="{{ route('competitions.index') }}"><span class="{{ trans('app.competitions-icon') }}"></span> {{ ucfirst(trans('app.competitions')) }}</a></li>
                                <li><a href="{{ route('modes.index') }}"><span class="{{ trans('app.modes-icon') }}"></span> {{ ucfirst(trans('app.modes')) }}</a></li>
                                <li><a href="{{ route('pages.index') }}"><span class="{{ trans('app.pages-icon') }}"></span> {{ ucfirst(trans('app.pages')) }}</a></li>
                                <li><a href="{{ route('reports.index') }}"><span class="{{ trans('app.reports-icon') }}"></span> {{ ucfirst(trans('app.reports')) }}</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ route('local-authorities.index') }}"><span class="{{ trans('app.local-authorities-icon') }}"></span> {{ ucfirst(trans('app.local-authorities')) }}</a></li>
                                <li><a href="{{ route('schools.index') }}"><span class="{{ trans('app.schools-icon') }}"></span> {{ ucfirst(trans('app.schools')) }}</a></li>
                            @endcan
                            @can('admin')
                                <li><a href="{{ route('classrooms.index') }}"><span class="{{ trans('app.classrooms-icon') }}"></span> {{ ucfirst(trans('app.classrooms')) }}</a></li>
                            @endcan
                            @can('super')
                                <li><a href="{{ route('users.index') }}"><span class="{{ trans('app.users-icon') }}"></span> {{ ucfirst(trans('app.users')) }}</a></li>
                            @endcan
                            @can('teach')
                             @if(!empty($user->classroom))
                                <li><a href="{{ route('trips.index') }}"><span class="{{ trans('app.trips-icon') }}"></span> {{ ucfirst(trans('app.trips')) }}</a></li>
                             @endif
                            @endcan
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Hi {{ $user->primary_name }} <span class="fa fa-caret-down"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ route('my-account.edit') }}">My account</a></li>
                        </ul>
                    </li>
                    <li>
                        @include('partials.logout')
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>