routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Authentication
Route::get(str_slug(trans('app.login')), 'Auth\LoginController@showLoginForm')->name('login');
Route::post(str_slug(trans('app.login')), 'Auth\LoginController@login');
Route::post(str_slug(trans('app.logout')), 'Auth\LoginController@logout')->name('logout');

// Registration
Route::get(str_slug(trans('app.register')), 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post(str_slug(trans('app.register')), 'Auth\RegisterController@register');

// Password Reset
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Application
Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // Base views
    Route::get('add-journeys', 'App\ViewController@index')->name('add-journeys');
    Route::get('compare', 'App\ViewController@index')->name('compare');
    Route::get('leaderboard', 'App\ViewController@index')->name('leaderboard');

    // User
    Route::get('my-account', 'MyAccountController@getAccount')->name('my-account.edit');
    Route::post('my-account', 'MyAccountController@postAccount')->name('my-account.update');
//  Route::get('my-classroom', 'MyAccountController@getClassroom')->name('my-classroom.edit');

    // App
    Route::group(['prefix' => 'app'], function () {

        Route::get('trips', 'App\JourneysController@index');
        Route::post('trips', 'App\JourneysController@index');

        Route::get('leaderboard', 'App\LeaderboardController@index');

        Route::get('compare/class', 'App\CompareController@classroom');
        Route::get('compare/year', 'App\CompareController@year');
        Route::get('compare/school', 'App\CompareController@school');

    });

    // Admin
    Route::group(['prefix' => 'admin'], function () {

        Route::get('options', 'Admin\OptionController@getOptions')->name('options.index');
        Route::post('options', 'Admin\OptionController@postOptions')->name('options.update');

        Route::resource('competitions', 'Admin\CompetitionsController');
        Route::resource('modes', 'Admin\ModesController', ['except' => ['create', 'destroy']]);

        Route::resource('local-authorities', 'Admin\LocalAuthoritiesController');
        Route::resource('schools', 'Admin\SchoolsController');
        Route::resource('classrooms', 'Admin\ClassroomsController');
        Route::resource('users', 'Admin\UsersController');
        Route::resource('pages', 'Admin\PagesController', ['only' => ['index', 'edit', 'update']]);

        Route::get('reports', 'Admin\ReportController@getIndex')->name('reports.index');
        Route::get('reports/users', 'Admin\ReportController@getUsersReport')->name('reports.users');
        Route::get('reports/schools', 'Admin\ReportController@getSchoolsReport')->name('reports.schools');
        Route::get('reports/trips', 'Admin\ReportController@getTripsReport')->name('reports.trips');
        Route::get('reports/year-group', 'Admin\ReportController@getYearGroupReport')->name('reports.year-group');

        Route::resource('trips', 'Admin\TripsController');

        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

});

Route::get('how-it-works', ['uses' => 'CustomPageController@getPage'])->name('how-it-works');
Route::get('terms-and-conditions', ['uses' => 'CustomPageController@getPage'])->name('terms-and-conditions');
Route::get('privacy-statement', ['uses' => 'CustomPageController@getPage'])->name('privacy-statement');

// Public
Route::get('leaderboard-public', 'App\ViewController@index')->name('leaderboard-public');
Route::group(['prefix' => 'app'], function () {
    Route::get('leaderboard-public', 'App\LeaderboardController@index');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
  use Notifiable;
  use SoftDeletes;

  protected $fillable = [
    'email',
    'school_id',
    'display_name',
    'first_name',
    'last_name',
    'is_admin',
    'is_super',
    'last_login',
    'last_login_ip',
    'password',
  ];

  protected $hidden = [
    'is_admin',
    'is_super',
    'last_login',
    'last_login_ip',
    'password',
    'remember_token',
    'created_at',
    'updated_at',
    'deleted_at'
  ];

  protected $dates = [
    'last_login',
    'created_at',
    'updated_at',
    'deleted_at'
  ];

  protected $casts = [
    'is_admin' => 'boolean',
    'is_super' => 'boolean',
  ];

  protected $appends = [
    'full_name',
  ];

  //region Events

//  protected static function boot()
//  {
//    parent::boot();
//
//    // set up new scope
//    $scope = new SortScope();
//    $self = new static;
//    $scope->attributes = $self->fillable;
//    static::addGlobalScope($scope);
//
//  }

  //endregion

  //region Relations

  public function classrooms()
  {
    return $this->belongsToMany(Classroom::class)->withTimestamps();
  }

  public function school()
  {
    return $this->belongsTo(School::class);
  }

  //endregion

  //region Authorization

  public function isAdmin()
  {
    return $this->is_admin;
  }

  public function isSuper()
  {
    return $this->is_super;
  }

  public function isTeacher()
  {
    return \DB::table('classroom_user')->select('user_id')->where('user_id', '=', auth()->user()->id)->count();
  }

//  public function owns($related)
//  {
//    return $this->id == $related->user_id;
//  }

  //endregion

  //region Accessors

  public function getClassroomAttribute()
  {
    return $this->classrooms->first();
  }

  public function getFullNameAttribute()
  {
    return $this->first_name . ' ' . $this->last_name;
  }

  public function getPrimaryNameAttribute()
  {

    // always return display name if present
    if (!empty($this->display_name)) {
      return $this->display_name;
    }

    // secondly, try the first name
    if (!empty($this->first_name)) {
      return $this->first_name;
    }

    // finally create a name using the users id
    return 'user' . $this->id;
  }

  //endregion

  //region Mutators

  public function setEmailAttribute($value)
  {
    $this->attributes['email'] = empty($value) ? null : strtolower(trim($value));
  }

  public function setDisplayNameAttribute($value)
  {
    $this->attributes['display_name'] = empty($value) ? null : trim($value);
  }

  public function setFirstNameAttribute($value)
  {
    $this->attributes['first_name'] = empty($value) ? null : trim($value);
  }

  public function setLastNameAttribute($value)
  {
    $this->attributes['last_name'] = empty($value) ? null : trim($value);
  }

  //endregion

  //region Static

  public static function selectList($school_id = null, $teacher_id = null)
  {
    // set up the query
    $query = User::query();

    // define the relation
    $relation = 'classrooms';

    // add the relation
    if (!empty($relation)) {
      $query = $query->with($relation);
    }

    // filter if necessary
    if (!empty($school_id)) {
      $query = $query->where('school_id', '=', $school_id);
    }

    // run the query
    $collection = $query
      ->orderBy('email', 'asc')
      ->get();

    // prepare the list
    $selectList = [];
    foreach ($collection as $model) {

      // default text
      //$assigned_text = '';

      // assigned text
      if (empty($model->classroom) || $model->id == $teacher_id) {
        //$assigned_text = ' - unassigned';
        // build the string
        //$selectList[$model->id] = $model->display_name . $assigned_text;
        $selectList[$model->id] = $model->first_name.' '.$model->last_name;
      }

    }

    // add the 'Please select' option
    $selectList = pleaseSelect($selectList);

    return $selectList;
  }

  //endregion

}

resources/views/admin/partials/admin-index.blade.php
test

resources/views/admin/partials/classrooms-create.blade.php
{{ Form::open(['route' => $resource . '.store']) }}
{{ Form::hidden('school_id', app('user')->school_id) }}
@can('super')
{{ Form::bsSelect('teacher_id', ucfirst(trans('app.teacher')), (empty(old('teacher_id')) ? null : old('teacher_id')), $userList, ['help' => '<a href="' . route('users.create') . '">Add a new ' . trans('app.user') . '</a>']) }}
@elsecan('admin')
{{ Form::hidden('teacher_id', app('user')->id) }}
@endcan
{{ Form::bsText('name', ucfirst(trans('app.classroom')) . ' name', old('name')) }}
{{ Form::bsSelect('year_group', 'Year group', (empty(old('year_group')) ? null : old('year_group')), $yearGroupList) }}
{{ Form::bsNumber('number_of_pupils', 'Number of pupils', old('number_of_pupils')) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/classrooms-edit.blade.php
{{ Form::model($model, ['route' => [$resource . '.update', $model->id], 'files' => true]) }}
{{ method_field('PATCH') }}
{{ Form::hidden('school_id', $model->school_id) }}
@can('super')
{{ Form::bsSelect('teacher_id', ucfirst(trans('app.teacher')), (empty($model->teacher) ? null : $model->teacher->id), $userList) }}
@elsecan('admin')
{{ Form::hidden('teacher_id', $model->teacher->id) }}
@endcan
{{ Form::bsText('name', ucfirst(trans('app.classroom')) . ' name', $model->name) }}
{{ Form::bsSelect('year_group', 'Year group', (empty($model->year_group) ? null : $model->year_group), $yearGroupList) }}
{{ Form::bsNumber('number_of_pupils', 'Number of pupils', $model->number_of_pupils) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/classrooms-index.blade.php
@if(!$assigned)
    @include('admin.components.model-add-button')
@endif
@if($collection->count())
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>@can('super') ID @endcan</th>
            <th>{{ ucfirst(trans('app.classroom')) }} name</th>
            <th>Year group</th>
            <th>{{ ucfirst(trans('app.teacher')) }} name</th>
            <th>School</th>
            <th>Assigned</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach ($collection as $model)
            <tr>
                <td>@can('super') {{ $model->id or '-' }} @endcan</td>
                <td>{{ $model->name or '-' }}</td>
                <td>{{ $model->year_group or '-' }}</td>
                <td>{{ $model->teacher->full_name or '-' }}</td>
                <td>{{ $model->teacher->school->name or '-' }}</td>
                <td>
                    @if(empty($model->teacher->pivot->updated_at))
                        -
                    @else
                        {{ $model->teacher->pivot->updated_at->format($options->date_format) }}
                    @endif
                </td>
                <td>
                @if(auth()->user()->id === $model['teacher']['id'])
                    @include('admin.components.model-action-buttons', ['edit' => true, 'delete' => true])
                @else
                    @can('super')
                        @include('admin.components.model-action-buttons', ['edit' => true, 'delete' => true])
                    @endcan
                @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

resources/views/admin/partials/competitions-index.blade.php
@include('admin.components.model-add-button')
@if($collection->count())
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Grace period</th>
            <th>Active</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($collection as $model)
            <tr>
                <td>{{ $model->id }}</td>
                <td>{{ $model->name }}</td>
                <td>{{ $model->start_date->format($options->date_format) }}</td>
                <td>{{ $model->end_date->format($options->date_format) }}</td>
                <td>{{ $model->grace_period->format($options->date_format) }}</td>
                <td>{{ $model->is_active ? 'Yes' : 'No' }}</td>
                <td class="text-right">
                    @include('admin.components.model-action-buttons')
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

resources/views/admin/partials/local-authorities-edit.blade.php
{{ Form::model($model, ['route' => [$resource . '.update', $model->id], 'files' => true]) }}
{{ method_field('PATCH') }}
{{ Form::bsText('name', 'Name', $model->name) }}
{{ Form::bsCheckbox('is_support', 'Is support?', $model->is_support) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/pages-edit.blade.php
@push('additional-header')
<link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
@endpush

{{ Form::model($model, ['route' => [$resource . '.update', $model->id]]) }}
{{ method_field('PATCH') }}
{{ Form::bsText('name', 'Title', $model->name) }}
{{ Form::bsText('url', 'URL', $model->url, ['readonly']) }}
{{ Form::bsTextArea('body', 'Body', $model->body, ['help' => 'Edit the page using <a target="_blank" href="https://daringfireball.net/projects/markdown/basics">markdown syntax</a>']) }}
<script>
    // instantiate the markdown editor
    var simplemde = new SimpleMDE({element: $("#body")[0]});
</script>
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/pages-index.blade.php
@if($collection->count())
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>URL</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($collection as $model)
            <tr>
                <td>{{ $model->name }}</td>
                <td><a href="{{ url('/') }}{{ $model->url }}" target="_blank">{{ $model->url }} <span class="fa fa-external-link fa-fw"></span></a></td>
                <td>
                    <form action="" class="text-right">
                        <a href="{{ route($resource . '.edit', $model->id) }}" class="btn btn-xs btn-default">Edit</a>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

resources/views/admin/partials/reports-edit.blade.php
<a target="_blank" class="btn btn-default" href="{{ route('reports.users') }}"><span class="fa fa-download fa-fw"></span> Download {{ trans('app.users') }} report</a><br><br>
<a target="_blank" class="btn btn-default" href="{{ route('reports.schools') }}"><span class="fa fa-download fa-fw"></span> Download {{ trans('app.schools') }} report</a><br><br>
<a target="_blank" class="btn btn-default" href="{{ route('reports.trips') }}"><span class="fa fa-download fa-fw"></span> Download {{ trans('app.trips') }} report</a><br><br>
<a target="_blank" class="btn btn-default" href="{{ route('reports.year-group') }}"><span class="fa fa-download fa-fw"></span> Download year group report</a>

resources/views/admin/partials/schools-create.blade.php
{{ Form::open(['route' => $resource . '.store']) }}
{{ Form::bsText('name', 'Name', old('name')) }}
{{ Form::bsCheckbox('is_support', 'Is support?', old('is_support')) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/schools-edit.blade.php
{{ Form::model($model, ['route' => [$resource . '.update', $model->id], 'files' => true]) }}
{{ method_field('PATCH') }}
{{ Form::bsText('name', 'Name', $model->name) }}
{{ Form::bsCheckbox('is_support', 'Is support?', $model->is_support) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}

resources/views/admin/partials/schools-index.blade.php
@include('admin.components.model-add-button')
@if($collection->count())
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach ($collection as $model)
            <tr>
                <td>{{ $model->id }}</td>
                <td>{{ $model->name }}</td>
                <td>
                    @include('admin.components.model-action-buttons', ['id' => $model->id])
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

resources/views/admin/partials/trips-index.blade.php
@include('admin.components.model-add-button')
@if($collection->count())
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                @can('super')
                    <th>ID</th>
                @endcan
                <th>Date</th>
                @can('super')
                    <th>Classroom</th>
                @endcan
                <th>Trips</th>
                <th>Points</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach ($collection as $model)
                <tr>
                    @can('super')
                        <td>{{ $model->id }}</td>
                    @endcan
                    <td>{{ $model->date->format(app('options')->date_format) }}</td>
                    @can('super')
                        <th>{{ $model->classroom->name }}</th>
                    @endcan
                    <td>{{ $model->total_trips }}/{{ $model->classroom->number_of_pupils }}</td>
                    <td>{{ $model->total_points }}</td>
                    <td>
                        @include('admin.components.model-action-buttons', ['id' => $model->id])
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endif

resources/views/admin/partials/users-create.blade.php
{{ Form::open(['route' => $resource . '.store']) }}
@can('super')
    {{ Form::bsSelect('school_id', 'School', old('school_id'), $schoolList) }}
@endcan
{{ Form::bsText('first_name', 'First name', old('first_name')) }}
{{ Form::bsText('last_name', 'Last name', old('last_name')) }}
{{ Form::bsText('display_name', 'Display name', old('display_name')) }}
{{ Form::bsText('email', 'Email', old('email')) }}
{{ Form::bsSubmit() }}
{{ Form::close() }}